### ISSUE TITLE
Team Size Not Properly Parsed

### ISSUE THREAD

**Issue by OfficialMMin** [CasvM/raid-tracker#1]
I had a raid with a team size of 12, and the log file recorded the team size as 1. Based on the code, it looks like you're just taking the first character available after the "Team Size: " in chat. This won't work for teams of 10+. Jagex also changed it so with larger team sizes, it doesn't display the exact size. For example, I think for team sizes of 11,12,13,14, and 15, it just says 11-15 in the chat. I'm not sure how you'll get the exact team size for these situations, but the current implementation doesn't support this.

**Comment by CasvM** [comment]
Ah! thanks for reporting the bug! I think i'll change it to say 11-15 in the tracker aswell if it's larger than 10, unless I can find a way to get the exact number of people in the raid.

**Comment by CasvM** [comment]
There's actually a variable to get the exact team size, which I will use for this variable in the future.
